name: Paul Barrett
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10719
title: Paul Barrett
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6e8b88'
    - '#fcd90c'
    - '#ce2d91'
    - '#433901'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
