name: Paul Barrett
favicon: null
layout_spectrum: 0.7678822875022888
typography_spectrum: 0.9164517414756119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6e8b88'
    - '#fcd90c'
    - '#ce2d91'
    - '#433901'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
